---
title: "Global Terrorism Plot 2"
output:
  html_document:
    code_folding: hide
    fig_height: 4.5
    fig_width: 7
    highlight: tango
    keep_md: true
    number_sections: yes
    theme: cosmo
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo=TRUE, 
                      error=FALSE,
                      fig.path = "README_figs/README-",
                      warning = FALSE)
```

```{r}
options(warn=-1)
```


```{r}
library(tidyr)
library(dplyr)
library(plotly)
library(rworldmap)
library(maps)
library(ggmap)
library(reshape2)
library(raster)
library(rgdal)
library(rgeos)

```

```{r}
global_t <- 
  terr %>%
  group_by(year,nation,Region) %>%
  summarize(Total=n())

global_y <- global_t%>%group_by(year)%>%summarize(Total=sum(Total))
global_attacks <- 
  global_t %>%
  group_by(nation) %>%
  summarize(Total=sum(Total)) %>% 
  arrange(desc(Total))
#%>%filter(Total>300)
#global_attacks$Total[which(is.na(global_attacks$Total))] = 0

attach(global_attacks)
global_n <- global_attacks[order(-Total),]
detach(global_attacks)
```


Let's look at the number of terrorist attacks with the passage of time.
```{r}
gy <- global_y %>%
  ggplot(mapping=aes(year,Total))+
  geom_line(color="red")+
  theme(legend.position="none", panel.background = NULL, axis.text.x = element_text(angle=45, vjust = 1))+
  labs(x="Year", y="Number of attacks", title="Number of global attacks over years")
ggplotly(gy, width = 800, height=480)
```

```{r}
global_kills_years <- 
  terr %>%
  group_by(year) %>%
  summarize(killed=sum(Killed))
global_wound_years <- 
  terr %>%
  group_by(year) %>%
  summarize(wounded=sum(wounded))
globe <- 
  global_kills_years %>% 
  inner_join(global_wound_years, by="year")

df <- melt(globe, "year")
df=rename(df, effect=variable)

gky <- df %>%
  ggplot(mapping=aes(x=year,y=value, color=effect))+
  geom_line()+
  theme(panel.background = NULL, axis.text.x = element_text(angle=45, vjust = 1))+
  labs(x="Year", y="Count", title="Number of people killed/wounded over years")
ggplotly(gky, width = 800, height=450)
```

# attacks by highest casualties(killed+wounded)
```{r}
#get weapon most used in each nation
terr$casualties=as.integer(terr$Killed+terr$wounded)
terr$casualties[which(is.na(terr$casualties))]=0
```


```{r}
g_max_cas <- terr%>%
  top_n(10, casualties) %>%
  ggplot(mapping=aes(x=reorder(target1, -casualties), y=casualties, fill=target1)) +
  geom_bar(stat = 'identity')+
  theme(legend.position="none", panel.background = NULL, axis.text.x =  element_text(angle=50, vjust = 1))+
  labs(x="Target of attack", y="Number of casulaties", title="Terrorist attacks with most casualties")
ggplotly(g_max_cas)
```

Let's look at the 40 countries with maximum number of terrorist attacks, and 40 countries with least number of terrorist attacks
```{r}
g2 <- global_n%>%
  top_n(40) %>%
  ggplot(mapping=aes(x=reorder(nation, -Total),y=Total,fill=nation)) + 
  geom_bar(stat='identity')+
  theme(legend.position="none", panel.background = NULL, axis.text.x = element_text(angle=90, vjust = 1))+
  labs(x="Countries", y="Number of attacks", title="Countries with most number of terrorist attacks")
  
ggplotly(g2, width = 800, height=450)

g2 <- global_n%>%
  top_n(-40)%>%
  ggplot(mapping=aes(x=reorder(nation, Total),y=Total,fill=nation)) + 
  geom_bar(stat='identity')+
  theme(legend.position="none", panel.background = NULL, axis.text.x = element_text(angle=90, vjust = 1))+
  labs(x="Countries", y="Number of attacks", title="Countries with least number of terrorist attacks")
ggplotly(g2, width = 800, height=450)
```